export const ADD_CHAT_MESSAGE = "ADD_CHAT_MESSAGE";
export const CHAT_SELECTOR = "CHAT_SELECTOR";
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const NEW_USER_LOGIN = 'NEW_USER_LOGIN'
export const CHANGE_USERNAME_BY_USER_ID = 'CHANGE_USERNAME_BY_USER_ID'
export const ADD_NEW_CHAT = 'ADD_NEW_CHAT '